#!/usr/bin/env python
#
# multi-line log grep
#

import re
import sys


##
## A pattern of a line of a beggining of log entry
## Default is something like 'Wed Nov 14 06:05:26 2012 GMT'
##
dow   = '(Mon|Tue|Wed|Thu|Fri|Sat)'
month = '(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)'
re_linehead = re.compile('^%s %s \d{1,2} \d\d:\d\d:\d\d 20\d\d [A-Z]{3,5} ' % (dow, month))



def mllgrep(pattern, ioin, ioout):
    is_matched = False

    logical_line = []
    for curline in ioin:
        if re_linehead.match(curline):
            logical_line = []
            is_matched = False

        if is_matched == True:
            ioout.write(curline)
            continue
        else:
            logical_line.append(curline)
            if pattern.search(curline):
                is_matched = True
                for l in logical_line:
                    ioout.write(l)



def main():
    if len(sys.argv) > 1 :
        pattern = re.compile(sys.argv[1])
    else:
        sys.stderr.write('ERROR: too few arguments\n')
        sys.exit(1)

    try:
        if len(sys.argv) > 2 :
            for fname in sys.argv[2:]:
                if fname == '-':
                    mllgrep( pattern, sys.stdin, sys.stdout)
                else:
                    mllgrep( pattern, open(fname), sys.stdout)
        else:
            mllgrep( pattern, sys.stdin, sys.stdout)
    except KeyboardInterrupt:
        sys.exit(0)




if __name__ == '__main__':
    main()
